
name: Test PowerShell on Ubuntu
on: 
  push:
  schedule:
    - cron: 10,16,25,31,49,55 15,16 * * *
  watch:
    types: started
jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         echo $(date +%F)
         .\AutoFuck_yqfk_V1.0.ps1 -username ${{secret.username}}  -psw ${{secret.psw}} 
         
